import { Container } from "./container.js"

export function Footer() {
  return (
    <Container>
      <footer className="border-t border-border py-6 text-center text-sm text-muted-foreground">
        Generated by -{" "}
        <a
          href="https://w3docs.vercel.app"
          target="_blank"
          className="font-medium text-foreground underline-offset-4 hover:underline"
        >
          w3docs
        </a>
      </footer>
    </Container>
  )
}
