/*
 * ╔══════════════════════════════════════════════╗
 * ║  This file is automatically generated by     ║
 * ║  Typest - typed asset paths for TypeScript.  ║
 * ║                                              ║
 * ║  Any edits you make here will be silently    ║
 * ║  overwritten the next time you run the dev   ║
 * ║  server or build your project.               ║
 * ║                                              ║
 * ║  To change which assets are included, edit   ║
 * ║  your vite config (typedAssets sources).     ║
 * ╚══════════════════════════════════════════════╝
 */

declare module "@typest/nextjs" {
  /* ╔══════════════════╗
     ║   Image Assets   ║
     ╚══════════════════╝ */
  const imageAssets: {
    readonly "logo-black.png": "/logo-black.png";
    readonly "logo-black.svg": "/logo-black.svg";
    readonly "logo-white.png": "/logo-white.png";
    readonly "logo-white.svg": "/logo-white.svg";
    readonly "opengraph.png": "/opengraph.png";
  };
  type ImageKey = keyof typeof imageAssets;
  export function imagePath(key: ImageKey): string;

  /* ╔══════════════════╗
     ║  Generic Assets  ║
     ╚══════════════════╝ */
  const genericAssets: {
    readonly "site.webmanifest": "/site.webmanifest";
  };
  type GenericKey = keyof typeof genericAssets;
  export function assetPath(key: GenericKey): string;

}
